// problem 2: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fn main() {
    let mut sum: int = 0;

    let mut pred = 1;
    let mut succ = 2;

    while succ < 4000000 {
        let step = succ;
        if step % 2 == 0 { sum += step; }

        succ += pred;
        pred = step;
    }

    println!("The sum is: {}", sum);
}
